version: "3"

services:
  db:
    build: .
    container_name: zenn_clone_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
volumes:
  db-store:
